### ISSUE TITLE
1.28 vs 1.29

### ISSUE THREAD

**Issue by juvian** [AiStudent/ghost-ent-bt#1]
Are you familiar with gameprotocol? I was wondering what would make playing with both players in 1.28v and 1.29v incompatible. I have managed to host a game and join from both versions, but as soon as game starts it gets desync. When disabling desync functionality, we are definitely seeing diferent things, as if actions from one player were not delivered successfully to the other.

From what I have seen in replay format, there are a few changes on replay header (version 6060 and an extra byte in playerRecord data), but actions remain the same. For what reason could actions not be delivered successfully between 1.28 and 1.29 if the action data on replays still follows same format?

**Comment by AiStudent** [comment]
I have never looked into the gameprotocol, except for the lobby part. Do you mean all three replays (1.29v, 1.28v, and ghost++) are the same? I have only briefly looked into replays, but if the ghost++ replay is the same as both others, it must also mean the wc3 client saves illegal incoming actions (since ghost++ can't tell what's a valid action or not). 

Then the different wc3 versions are perhaps setting different ID values for each unit.

Perhaps you could try setting full shared control of units in a 1v2 game (where 2 players on the same team have different wc3 versions, and the opposing team is a fakeplayer). I guess you can either print the move-action packets in [w3g](https://github.com/scopatz/w3g) (I saw now you have made your own implementation in js, well done!).

If you move 1 unit first with 1.28, and then with 1.29, I guess w3g should print different unit IDs for moving the same unit. 

I'd be happy to hear your findings or progress in general.

**Comment by juvian** [comment]
Haven`t looked at ghost++ replay, forgot it could be enabled. Will do a test on the weekend and compare 1.28, 1.29 and ghost replay, thanks. Will keep you updated

**Comment by juvian** [comment]
Well, not sure what to make of it. wonder if the cause is the difference of additionalDataSize on playerRecord.

This is 1.28 vs 1.29: https://www.diffchecker.com/eOuvIqmO
This is 1.28 vs ghost: https://www.diffchecker.com/Mh5TkwlC

**Comment by AiStudent** [comment]
Very nice comparsion.
This was with desync enabled right? What about when desync is disabled? I'd be happy if you wanted to share 2 replays where desync is disabled and you move one unit with shared control. 

If the unit IDs are different perhaps a ID translation table could work. If all the units IDs follow a pair-pattern, perhaps it can be solved.

All these are empty actions I assume?
[] parsed-time-slot
31 parsed-block
34 parsed-block

**Comment by juvian** [comment]
Unfortunately I can not compile ghost on windows, so can`t really try it. When I tried with desync disabled it was with aura bot, but that one doesn`t save replay. I can still try with aura with desync disabled and just compare 1.28 to 1.29 player replays though.

[] parsed-time-slot is empty actions, 31 parsed-block is finished parsing a block of type time slot and 34 is finished parsing a block of type checksum

**Comment by juvian** [comment]
I tried as you said a simple melee map with shared units. Replay broke my parser so still need to fix it for more details, but:
1) Pinging did work
2) chat works
3) transfer resources works
4) moving units/upgrading building doesn`t work

Si its highly likely that it is as you said, units having different ids.
As for checksum, added that info on previous replay and indeed first checksum from both players is already different, before any actions happened, I would guess first checksum is made from replay header, which changes with 6060 version. Will try to fix parser today and post results

**Comment by AiStudent** [comment]
I did some tests and they are inconclusive. Only race and map seemed to affect. Not colors or starting position. I used w3g (it crashed with colors on some maps).
All initially created units seem to have an increased value (everything in hex):

With 2 players:
+01E0 0000 01E0
For example (tested all workers for 4 games):
128 starting unit id -> 129 starting unit id
3a7200003a72 -> 3c5200003c52 = increase of 01E0 0000 01E0

4p map with 3 comps:
+0150 0000 0150

For one newly created peon there was some other increase (tested once).
2p map:
+00F1 0000 0198

4p map with 3 comps:
+02F7 FFFF F88A

I was happy at first with +1E0 but then it proved to be more complex..

**Comment by juvian** [comment]
You think we can chat on discord?

**Comment by AiStudent** [comment]
Yeah sure. My tag is Wc3Addict#7376

**Comment by AiStudent** [comment]
Final results:
Here are the results from a test some weeks ago. I checked if using the exact same build order on the same map would affect the unit ID's differently. This was the testing procedure for orc on booty bay.

Build order:
Build burrow.
Build altar.
Build far seer.
Summon 2 wolfs.

Then we select some units to see their unit ID in the replay.
Select right up worker (the worker at 2-o'clock of all 5 starting workers).
Select wolf1, wolf2.
Select far seer.
Select altar.
Select burrow.

1.26 unit ID's:
0x30bc000030bc (starting peon)
0x3dbb000031b5 (wolf 1)
0x3daa0000315c (wolf 2)
0x3c7700003169 (far seer)
0x37760000317b (altar)
0x386c00003034 (burrow)

1.29 unit ID's:
0x329c0000329c  (starting peon)
0x407900003354 (wolf 1)
0x406800003338  (wolf 2)
0x3edf00003215  (far seer)
0x39df000033a6   (altar)
0x3abd000033c8  (burrow)

The difference for every unit (1.29 value minus 1.26):
0x1E0000001E0 (starting peon. This difference seem to be the same for all starting units.)
0x2BE000001DC (summoned wolf 1)
0x2BE0000019F (summoned wolf 2)
0x268000000AC (far seer)
0x2690000022B (altar)
0x25100000394 (burrow)

Since the newly created units have different change in unit ID, it is probably not realizable to overcome this barrier with ghost++ for cross-version hosting.
